### ISSUE TITLE
Error about config.scpt when using

### ISSUE THREAD

**Issue by mttjhn** [caleb531/play-song#53] opened 2019-04-03 21:08 UTC
I'm getting the following error in the debug when attempting to search for a song using the `playsong` command... is there a setup step I missed? I simply downloaded the .alfredworkflow file and installed it.  I attempted to `clearcache`, but no improvement.

`[ERROR: input.scriptfilter] Code 1: filters/playsong.applescript:48:120: execution error: Can’t make file "Macintosh HD:Users:matthew:Library:Caches:com.runningwithcrayons.Alfred-3:Workflow Data:com.calebevans.playsong:config.scpt" into type file. (-1700)`

**Comment by caleb531** [comment] 2019-04-03 21:09
@mttjhn What version of macOS / OS X are you running? Also, what version of Alred are you using?

**Comment by mttjhn** [comment] 2019-04-03 21:13
@caleb531 I'm on Mojave 10.14.4 and using Alfred v3.8.1

**Comment by mttjhn** [comment] 2019-04-03 21:15
Also, getting the above error regardless of which command I run (e.g. `playartist`, `playsong`, etc)

**Comment by caleb531** [comment] 2019-04-06 16:28
@mttjhn Hmm okay, stupid question, but I have to ask: did you make sure to download `Play Song (Alfred 3).alfredworkflow` and not `Play Song (Alfred 2).alfredworkflow`?

**Comment by mttjhn** [comment] 2019-04-09 19:23
Yes, I'm using the Alfred 3 version. I managed to get it working by manually executing the `osacompile` command that's in the compile-config.sh script to generate the config.scpt file and then copied that to the correct folder where it was missing.

**Comment by caleb531** [comment] 2019-04-09 19:26
@mttjhn Good to know. I'm surprised it didn't run automatically, because the code it set up to. Maybe it's a permission issue?

Well, if you have things working now, then I'll close this issue. Thanks for reaching out.

**Closed by caleb531** 2019-04-09 19:26 UTC

**Comment by caleb531** [comment] 2019-04-21 22:31
@mttjhn Good news! I was able to find the root cause of this error, and have pushed Play Song v5.0.2 with a fix. Please check out https://github.com/caleb531/play-song/releases/tag/v5.0.2 and let me know if things are still working for you.

**Comment by mttjhn** [comment] 2019-04-23 15:59
Excellent! I just downloaded the new workflow and it works great without any extra steps. Thanks for the quick turnaround.
