### ISSUE TITLE
playplaylist shows no result when there are too many matches

### ISSUE THREAD

**Issue by alexmerkel** [caleb531/play-song#25] opened 2015-01-27 16:21 UTC
I have a lot (>30) of playlist that start with "Best-Of:".
When using playplaylist, no result is shown until I limit the matches, e.g "Best-Of: R". Following error is given while typing Best-Of:

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 1660:1671: execution error: The variable resultLimit is not defined. (-2753)
```

**Comment by Tyilo** [comment] 2015-01-27 16:43
The problem is probably here: https://github.com/caleb531/play-song/blob/master/filters/filter-playlists.applescript#L48

I think `resultLimit` should be replaced by `(config's resultLimit)`.

**Comment by caleb531** [comment] 2015-01-27 16:56
Ah, you are indeed correct. I'll push out a fix for this and for the disableShuffle() handler later today.

Caleb

**Comment by caleb531** [comment] 2015-01-27 19:35
Fixed in the latest commit. Will push a new release (v3.0.3) now.

**Closed by caleb531** 2015-01-27 19:35 UTC
Labels: bug
