### ISSUE TITLE
Playback stops after ~25-seconds after "play playlist" on a Apple Music Playlist

### ISSUE THREAD

**Issue by ronaldmendoza** [caleb531/play-song#49] opened 2018-06-06 23:00 UTC
Playback stops ~10-45 seconds after using workflow "play playlist" on an Apple Music Playlist.

Running itunes 12.7.5.9
macos 10.13.4
2017 mbp 13" non-touchbar

Repro Steps:
1. Add all of these Apple Music Playlists to your iTunes Library:
```
> open "itmss://itunes.apple.com/us/playlist/primavera-sound-2018-barcelona/pl.9d153d7b2bc94e5983a510115cdc2410"
> open "itmss://itunes.apple.com/us/playlist/pure-yoga/pl.6e7eb6c06bcd40ec982e24d6af0cd59a"
> open "itmss://itunes.apple.com/us/playlist/the-a-list-dance/pl.6bf4415b83ce4f3789614ac4c3675740"
```

2. Click +ADD from within iTunes for the Apple Music Playlist 
3. In iTunes observe playlist now appears in "Apple Music Playlist"
4. In alfredapp try "play playlist" <playlist name>
5. Observe "Alfred Play Song" is populated in iTunes under 'Music Playlists'
6. Playlist starts and first song plays.
7. Observe stops after n-seconds (time varies)
8. "Alfred Play Song" Playlist becomes 'empty'

**Comment by caleb531** [comment] 2018-06-08 02:38
@ronaldmendoza Thank you for providing the steps and some example playlists—I am able to reproduce exactly what you are experiencing. For the time being, you can hold down the *shift* key when choosing the playlist from the results. This will play the playlist directly, rather than queueing up all the songs in the Alfred Play Song playlist.

If you do not desire to hold down `shift` every time, you can modify the workflow to do so by deleting the non-modifier link for `playplaylist`, and then double clicking the `shift` link to remove the modifier.

**Steps:**

![step-1](https://user-images.githubusercontent.com/872474/41136216-1550a2f0-6a8a-11e8-9bfc-fef2c24b2f40.png)
![step-2](https://user-images.githubusercontent.com/872474/41136217-156a15f0-6a8a-11e8-965e-e901221e302c.png)
![step-3](https://user-images.githubusercontent.com/872474/41136218-1582b20e-6a8a-11e8-9f02-76ecaaf2959f.png)

**Result**

![result](https://user-images.githubusercontent.com/872474/41136227-208af792-6a8a-11e8-8641-b2e978b7d5e9.png)

I hope that will serve as a workaround for the time being. I am leaving this issue open because it is still not the desired behavior, thereby warranting additional investigation.

**Comment by caleb531** [comment] 2018-06-09 01:43
@ronaldmendoza After some further investigation, I have identified the cause of the problem, and will be pushing out a fix soon. The patch will be part of Play Song v5, but I will attach the beta workflow to this issue as soon as I finish the patch.

In other words, hang tight—a fix is on the way!

**Comment by caleb531** [comment] 2018-06-09 04:11
@ronaldmendoza @spott I've finished the fix! Apple Music playlists will now play properly, however as a consequence of fixing the bug, they can no longer be queued (not too much of a loss, IMO—regular user playlists can still be queued).

Please try out the attached build (v5-beta.3) and let me know how it works for you.  
[Play Song v5-beta.3.alfredworkflow.zip](https://github.com/caleb531/play-song/files/2086616/Play.Song.v5-beta.3.alfredworkflow.zip)

**Closed** 2018-06-15 19:19 UTC
Labels: bug

**Comment by spott** [comment] 2018-07-27 17:08
@caleb531:

Thanks!  Great to hear that you got this.  I'll give the fix a try and see if it works for me.
